### ISSUE TITLE
可视化不正确的问题

### ISSUE THREAD

**Issue by CherryXiao1** [xiaoqiang-cheng/Oviz#1]
感谢您所做的贡献！
当我在可视化其他数据集时，比如kitti数据集，3Dbbox的框无法准确的框在目标上，以及点云整体会有在车身的上方，还请您指教

**Comment by xiaoqiang-cheng** [comment]
> 感谢您所做的贡献！ 当我在可视化其他数据集时，比如kitti数据集，3Dbbox的框无法准确的框在目标上，以及点云整体会有在车身的上方，还请您指教

你好，

你可以提供视频或者图片来方便debug。点云或者bbox等显示异常的原因可以从以下几个角度分析。

由于Oviz期望是一款通用的可视化工具，因此您必须清楚的知道要可视化的点云维度，并正确配置 dim和xyz的维度。如果正确配置后，点云分布正常，应该就是正常的。
bbox 显示同理，需要正确指定bbox配置的维度以及旋转。
您可以先检查配置，并上传问题图片或者视频，或者提供几帧您的点云和bbox的数据文件，方便我们后续检查。

祝好，
Xiaoqiang
