### ISSUE TITLE
能否提供本地可视化的示例代码和数据？

### ISSUE THREAD

**Issue by zouyuanpeng** [xiaoqiang-cheng/Oviz#2]
你好，我看了下readme，还是不太能理解如何在本地可视化occ和图像。可以提供一个简单的本地可视化的demo脚本和对应的样例数据吗，这样可以更方便上手调试。谢谢～

**Comment by zouyuanpeng** [comment]
已解决

**Comment by xiaoqiang-cheng** [comment]
我会提供一份demo 在release，并描述相关说明
