### ISSUE TITLE
显示OCC时候wlh设置为0.1,0.1,0.1时候无法显示

### ISSUE THREAD

**Issue by zouyuanpeng** [xiaoqiang-cheng/Oviz#3]
我这边使用oviz显示occ时候（occ以点云格式保存，pcd格式，每行为 x，y，z，label）
ElementSetting->template->pointcloud中勾选voxel模式，当w,l,h设置为-1时候可以显示occ，如下图1所示；我的w,l,h实际大小为（0.1,0.1,0.1），当改称0.1,0.1,0.1，或者其他非-1数字时，occ就无法显示，如图2所示。想问下该如何设置呢？我电脑系统是ubuntu2204 。
![20241207-165449](https://github.com/user-attachments/assets/12dabcfc-2fca-44b0-9c38-52c60e592d22)
![20241207-165412](https://github.com/user-attachments/assets/8b1f84e0-2807-45ee-a04d-17a1eede84ed)

**Comment by xiaoqiang-cheng** [comment]
这里无法调整 w l h 的原因是， oviz 界面上，point cloud wlh 需要填充的内容是 数据中的 “维度”，一切信息来自于数据本身，这是在设计时重点考虑的选择，特别是为了兼容未来可能出现的每个 occ size 不一样的情况。

所以，你有三种办法解决这个问题，我理解你是想修改 voxel 尺寸为 0.1m


1. 将你的 data array 整理为如下格式

x y z label w l h，保存为 二进制格式.bin，重新选择数据，并在界面指定 wlh 为 4，5，6

2. 同上数据组织，但是定制化保存为 pcd 格式，同样的，你需要指定上述维度。

3. 直接修改代码，建议你使用源码安装的方式使用，修改源码中一处硬代码 0.4 改为 0.1。 这个参数后续升级会留接口出来，你自用可以先这样快速解决。
